name: payment Deploy to ECR

on:
  # push:
  #   branches: [ master ]
  push:
    branches: [ payment ]
  # task_def로 main.yaml은 사용하지 않음
  # push:
  #   branches: [ main ]

jobs:

  build:

    name: Build Image
    runs-on: ubuntu-latest

    steps:

    - name: Check out code
      uses: actions/checkout@v2

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-northeast-2

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1
      
    - name: Build, tag, and push image to Amazon ECR
      run: |
        docker build -t terraform_payment ./payment
        docker tag terraform_payment:latest 997059781683.dkr.ecr.ap-northeast-2.amazonaws.com/terraform_payment:latest
        docker push 997059781683.dkr.ecr.ap-northeast-2.amazonaws.com/terraform_payment:latest
